apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-kubernetes
spec:
  workspaces:
  - name: source
  steps:
  - name: deploy
    image: bitnami/kubectl:latest
    script: |
      cd $(workspaces.source.path)/kubernetes
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
