apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubernetes-actions
  namespace: tekton-pipelines
spec:
  params:
    - name: script
      description: The script to run
      type: string
  steps:
    - name: kubectl
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e
        $(params.script)