apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: weather-app-pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
  - name: image-tag
    type: string
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
  
  - name: build
    taskRef:
      name: build-weather-app
    runAfter:
    - git-clone
    workspaces:
    - name: source
      workspace: shared-workspace
  
  - name: deploy
    taskRef:
      name: deploy-to-kubernetes
    runAfter:
    - build
    workspaces:
    - name: source
      workspace: shared-workspace
