apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: weather-app-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: URL of the git repo
    - name: git-revision
      type: string
      description: Revision to checkout (branch, tag, sha, ref…)
      default: main
    - name: image-name
      type: string
      description: Name of the image to build
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    - name: build-image
      taskRef:
        name: kaniko-ecr
        kind: Task
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: DOCKERFILE
          value: src/Dockerfile
        - name: CONTEXT
          value: "."
      runAfter:
        - fetch-source
    - name: deploy
      taskRef:
        name: helm-upgrade
        kind: Task
      params:
        - name: charts_dir
          value: "./weather-app-chart"
        - name: release_name
          value: "weather-app"
        - name: release_namespace
          value: "weather-app"
        - name: upgrade_extra_params
          value: "--install"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-image