apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: weather-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-key
              key: WEATHER_API_KEY
        resources:
          {{- toYaml .Values.resources | nindent 12 }}