apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: weather-api-key
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: weather-api-key
    creationPolicy: Owner
  data:
    - secretKey: WEATHER_API_KEY
      remoteRef:
        key: weather-app/api-key
        property: WEATHER_API_KEY