apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-data-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeBindingMode: WaitForFirstConsumer
  resources:
    requests:
      storage: {{ .Values.storage.size }}