apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-ecr
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      description: Name of the image to build
    - name: DOCKERFILE
      description: Path to the Dockerfile to build
      default: src/Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko
      default: "."
    - name: EXTRA_ARGS
      description: Extra arguments to pass to Kaniko
      type: array
      default: []
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built
    - name: IMAGE_URL
      description: URL of the image just built
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.9.0-debug
      env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
        - name: AWS_REGION
          value: "eu-north-1"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --digest-file=/tekton/results/IMAGE_DIGEST
        - --aws
        - $(params.EXTRA_ARGS)
      securityContext:
        runAsUser: 0
    - name: write-url
      image: docker.io/library/bash:5.1.4
      script: |
        set -e
        echo -n "$(params.IMAGE)" > $(results.IMAGE_URL.path)