replicaCount: 2

image:
  repository: 
  tag: latest
  pullPolicy: Always

serviceAccount:
  roleArn: "arn:aws:iam::595965639663:role/weather-app-secrets-role"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

storage:
  storageClassName: gp3
  size: 3Gi
